### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by cbellino** [cbellino/ayl-dashboard#1]
- [ ] Allow edition of the instances
- [ ] Add better analytics: https://github.com/mozilla/react-ga
- [ ] Add unit tests for components
- [ ] 100% coverage: https://coveralls.io/
- [ ] Automatic deployments on build success
- [ ] Reduce the size of `main.js` to a minimum
- [ ] Render the app on the server again (isomorphic)
- [ ] Remove dev tools from the production build
- [ ] Move DevTools > MonitorToolbar to an external plugin
- [ ] Add back a link to open the instance
- [ ] Update the logo and style of the app
