### ISSUE TITLE
Roadmap 1.1

### ISSUE THREAD

**Issue by cbellino** [cbellino/ayl-dashboard#2]
- [ ] Allow to sign in via github.
- [ ] Replace the user text input by a list of users.
- [ ] Display notifications when an instance is updated.
- [ ] Lock instance when editing ?
